kuw/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),

    path("faq", views.faq, name="faq"),

    path("success", views.success, name="success"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path("", include("kuw.urls")),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kuw/models.py
#from email import message
from django.db import models
from django.utils.html import mark_safe

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=100)
    photo = models.ImageField(null=True, blank=True, upload_to="images/")
    message = models.TextField()
    availability = models.TextField(default="", null=True, blank=True,)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created",)

    def img_preview(self): #new
        return mark_safe(f'<img src = "{self.photo.url}" width = "300"/>')

    def __str__(self):
        return self.email

kuw/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

kuw/views.py
from django.shortcuts import redirect, render
from .forms import ContactForm
from django.core.mail import send_mail
from django.conf import settings

def home(request):
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()

            details = f'Enquiry from: {form.cleaned_data["name"]}'
            email = form.cleaned_data["email"]
            phone = form.cleaned_data["phone"]
            message = form.cleaned_data["message"]
            photo = form.cleaned_data["photo"]
            availability = form.cleaned_data["availability"]
            web_link = "https://krissisitedeploy.onrender.com/admin/login/"

            send_mail(details, #subject
                        f"NAME:\n {form.cleaned_data['name']}\n\n PHONE:\n {phone}\n\n EMAIL:\n {email}\n\n MESSAGE:\n {message}\n\n PHOTO:\n {photo.url}\n\n AVAILABILITY:\n {availability}\n\n VIEW FULL ENQUIRY:\n{web_link}",  #message
                        None, # from
                        settings.ADMIN_EMAILS) #to
            return redirect ('success')

    form = ContactForm()
    context = {'form': form}
    return render(request, "kuw/home.html", context)

def faq(request):
    return render(request, "kuw/faq.html")

def success(request):
    return render(request, "kuw/success.html")

kuw/templates/kuw/about-sec.html
{% load static %}

<section class="page-section bg-primary" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">A TATTOO FROM THE HEART</h2>
                <hr class="divider divider-light" />
                
                <small class="text-white-75 mb-5"><i class="bi bi-dot"></i>Vegan Ink</small>
                <br>
                <small class="text-white-75 mb-5"><i class="bi bi-dot"></i>Personalised Consultation</small>
                <br>
                <small class="text-white-75 mb-5"><i class="bi bi-dot"></i>Aftercare and Touch-Ups</small>
                <br>
                <small class="text-white-75 mb-5"><i class="bi bi-dot"></i>Queer and Neurodivergent Friendly</small>
                <br>
            </div>
        </div>
    </div>
</section>

kuw/templates/kuw/contact-sec.html
{% load static %}

<section class="page-section bg-primary" id="contact">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 col-xl-6 text-center">
                <h2 class="text-white mt-0">Enquiry Form</h2>
                <hr class="divider divider-light" />
                <p class="text-muted mb-5">To book an appointment, please fill out the form below! <br> <small>Unsure what to write? Click <a href="faq">here</a> to read my FAQ.</small></p>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
            <div class="col-lg-6">
                <!-- FORM -->
                <form action="" method="post" id="contactForm" enctype="multipart/form-data" data-sb-form-api-token="API_TOKEN">
                    {% csrf_token %}
                    <!-- Name input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" type="text" name="name" maxlength="200" required="" id="id_name" placeholder="Enter your name..." data-sb-validations="required" />
                        <label for="name">Full name</label>
                        <div class="invalid-feedback" data-sb-feedback="id_name:required">A name is required.</div>
                    </div>
                    <!-- Email address input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" type="email" name="email" maxlength="254" required="" id="id_email" placeholder="name@example.com" data-sb-validations="required,email" />
                        <label for="email">Email address</label>
                        <div class="invalid-feedback" data-sb-feedback="id_email:required">An email is required.</div>
                        <div class="invalid-feedback" data-sb-feedback="id_email:email">Email is not valid.</div>
                    </div>
                    <!-- Phone number input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" type="tel" name="phone" maxlength="100" required="" id="id_phone" placeholder="(123) 456-7890" data-sb-validations="required" />
                        <label for="phone">Phone number</label>
                        <div class="invalid-feedback" data-sb-feedback="id_phone:required">A phone number is required.</div>
                    </div>
                    <!-- Message input-->
                    <div class="form-floating mb-3">
                        <textarea class="form-control" type="text" name="message" cols="40" rows="10" required="" id="id_message" placeholder="Enter your message here..." style="height: 6rem" data-sb-validations="required"></textarea>
                        <label for="message">Your Idea</label>
                        <div class="invalid-feedback" data-sb-feedback="id_message:required">A message is required.</div>
                    </div>
                    <!-- Photo input-->
                    <div>
                        <small class="text-muted mb-5">  Upload reference photo here: </small>
                        <br>
                        <label class="custom-file-upload">
                        <input class="form-control" type="file" name="photo" cols="40" rows="10" width="10" required="" accept="image/*" id="id_photo">
                        </label>
                        <br><br>
                    </div>
                    <!-- Availability input-->
                    <div class="form-floating mb-3">
                        <textarea class="form-control" type="text" name="availability" cols="40" rows="10" required="" id="id_message" placeholder="Enter your message here..." style="height: 3.5rem" data-sb-validations="required"></textarea>
                        <label for="message">Availability</label>
                        <div class="invalid-feedback" data-sb-feedback="id_message:required">A message is required.</div>
                    </div>
                    <!-- Submit Button-->
                    <div class="d-grid">
                        <input class="btn btn-primary btn-xl" type="submit" value="Submit">
                    </div>   
                </form>
            </div>
        </div>
    </div>
</section>

<style>
    .custom-file-upload {
        padding: 10px 0px;
        display: inline-block;
        cursor: pointer;
}
</style>

kuw/templates/kuw/delete.html
{% extends 'index.html' %}

{% block content %}

<section class="page-section bg-primary" id="faq">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">

                <h2 class="text-white mt-0">Delete Submisson?</h2>
                <hr class="divider divider-light"/>

                    <div>
                        <form method="POST" action="">
                            {% csrf_token %}
                            <p class="text-white-75 mb-5">Are you want to delete the submisson from "{{obj}}"?</p>
                                <a href="{{request.META.HTTP_REFERER}}">Go back</a> 
                                <i class="bi bi-dot"></i>
                            <input type="submit" value="Confirm" class="btn btn-success">
                        </form>
                        <hr class="divider divider-light"/>
                    </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

kuw/templates/kuw/faq.html
{% extends 'index.html' %}

{% block content %}
<section class="page-section bg-primary" id="faq">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">

                <h2 class="text-white mt-0">FAQ</h2>
                <hr class="divider divider-light"/>

                <h4 class="text-white mt-0">How do I book an appointment?</h4>
                <small class="text-white-75 mb-5">You can book an appointment 
                    by filling out a contact form with your details and tattoo idea. 
                    I will contact you by email to confirm an appointment. <br> Alternatively,
                    you can send me a message on my instagram, with your idea and availability. 
                    (Find my social media link in the footer)</small>
                    <hr class="divider divider-light"/>

                    <h4 class="text-white mt-0">How much will my tattoo cost?</h4>
                <small class="text-white-75 mb-5">Tattoo prices vary depending on the design, 
                    size, and complexity. For an accurate price estimate, 
                    please send me a message or book a consultation appointment.</small>
                    <hr class="divider divider-light"/>

                    <h4 class="text-white mt-0">How should I prepare for my tattoo appointment?</h4>
                <small class="text-white-75 mb-5">Avoid alcohol and aspirin 24 hours before your appointment. 
                    Make sure to eat a good meal and stay hydrated. 
                    Wear comfortable clothing that allows easy access to the area you're getting tattooed.</small>
                    <hr class="divider divider-light"/>

                    <h4 class="text-white mt-0">Can I bring my own design?</h4>
                <small class="text-white-75 mb-5">Yes, I welcome custom designs! 
                    Feel free to bring in your own design or collaborate with me
                    to create a unique tattoo that suits your style.</small>
                    <hr class="divider divider-light"/>

                    <h4 class="text-white mt-0">What if I need to reschedule or cancel my appointment?</h4>
                <small class="text-white-75 mb-5">Please contact me at least 48 hours in advance 
                    if you need to reschedule or cancel your appointment. Deposits are non-refundable, 
                    but we can transfer them to a new appointment date within a reasonable timeframe.</small>
                    <hr class="divider divider-light"/>

                    <h4 class="text-white mt-0">Do you offer touch-ups?</h4>
                <small class="text-white-75 mb-5">Yes, I offer touch-ups for my tattoos. 
                    Please send me a message to schedule a touch-up appointment if needed.</small>
                    <hr class="divider divider-light"/>

                    <h4 class="text-white mt-0">Can I see examples of your previous work?</h4>
                <small class="text-white-75 mb-5">Absolutely! You can view my portfolio on my website 
                    or social media page.</small>
                    
                <br>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

kuw/templates/kuw/home.html
{% extends 'index.html'%}

{% block content %}

    <!-- Masthead -->
    {% include 'kuw/masthead-sec.html' %}
    <!-- About-->
    {% include 'kuw/about-sec.html' %}
    <!-- Portfolio -->
    {% include 'kuw/portfolio-sec.html' %}
    <!-- Contact -->
    {% include 'kuw/contact-sec.html' %}

{% endblock content %}

kuw/templates/kuw/masthead-sec.html
{% load static%}

<header class="masthead">
    <div class="container px-4 px-lg-5 h-100">
        <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-end">
                <h1 class="text-white font-weight-bold">Krissi U.</h1>
                <small class="text-white font-weight-bold">Surrealism 
                    <i class="bi bi-dot"></i> Black & Grey 
                    <i class="bi bi-dot"></i> Neotraditional</small>
                <hr class="divider divider-light" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                
                <div><a class="btn btn-primary btn-xl" href="#contact">Book Now</a></div>
                <br>
                <div><a class="btn btn-primary btn-xl" href="#portfolio">Portfolio</a></div>
            </div>
        </div>
    </div>
</header>

kuw/templates/kuw/portfolio-sec.html
{% load static %}

<div id="portfolio">
    <div class="container-fluid p-0">
        <div class="row g-0">
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/1.jpg' %}">
                    <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/1.jpg' %}" alt="..." />
                    <div class="portfolio-box-caption">
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/2.jpg' %}">
                    <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/2.jpg' %}" alt="..." />
                    <div class="portfolio-box-caption">
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/3.jpg' %}">
                    <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/3.jpg' %}" alt="..." />
                    <div class="portfolio-box-caption">
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/4.jpg' %}">
                    <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/4.jpg' %}" alt="..." />
                    <div class="portfolio-box-caption">
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/5.jpg' %}">
                    <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/5.jpg' %}" alt="..." />
                    <div class="portfolio-box-caption">
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/6.jpg' %}">
                    <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/6.jpg' %}" alt="..." />
                    <div class="portfolio-box-caption p-3">
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/7.jpg' %}">
                    <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/7.jpg' %}" alt="..." />
                    <div class="portfolio-box-caption">
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/8.jpg' %}">
                    <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/8.jpg' %}" alt="..." />
                    <div class="portfolio-box-caption">
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

kuw/templates/kuw/submissons.html
{% extends 'index.html' %}

{% block content %}

<style>
    .submisson-container {
    display: grid;
    grid-template-columns: 40% 10% 40%;}
</style>

{% for submisson in submissons %}
<section class="page-section bg-primary" id="submissons_feed">
    <div class="submisson-container">

        <div class="col-lg-8 text-center">
            <h5 class="text-white mt-0">Name:</h5>
            <small class="text-white-75 mb-5">{{submisson.name}}</small>
            <br><br>

            <h5 class="text-white mt-0">Email:</h5>
            <small class="text-white-75 mb-5">{{submisson.email}}</small>
            <br><br>
            <button class="btn btn-primary" onclick="window.location.href='mailto:{{submisson.email}}'">Send Email</button>
            <br><br>

            <h5 class="text-white mt-0">Phone:</h5>
            <small class="text-white-75 mb-5">{{submisson.phone}}</small>
            <br>

            <hr class="divider divider-light"/>
        </div>

        <div class="col-lg-8 text-center">

            <h5 class="text-white mt-0">Availability:</h5>
            <small class="text-white-75 mb-5">{{submisson.availability}}</small>
            <br> <br>

            <hr class="divider divider-light"/>

            <button class="btn btn-danger btn-sm" style="width:100px;height:30px;font-size:small;"
            onclick = "window.location.href='{% url 'delete_submisson' submisson.id %}';">Delete</button>
        </div>

        <div>
            {% if submisson.photo %}
            <img src="{{ submisson.photo.url }}" width="500">
            {% endif %}
            <br> <br>
            <small class="text-white-75 mb-5">{{submisson.message|linebreaks}}</small>
        </div>
    </div>
</section>
<div class="page-section"></div>
{% endfor %}

{% endblock %}

kuw/templates/kuw/success.html
{% extends 'index.html' %}

{% block content %}
<section class="page-section bg-primary" id="success">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">

                <h2 class="text-white mt-0">Success!</h2>
                <hr class="divider divider-light"/>

                <h4 class="text-white mt-0">Your message has been sent to Krissi!</h4>
                <small class="text-white-75 mb-5">You should recieve a reply back soon. <br> (Please make sure your email is correct and you check your junk folder.)</small>
                    <hr class="divider divider-light"/>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/footer.html
{% load static %}

<footer class="bg-light py-5">
    <div class="container px-4 px-lg-5">
        <div class="small text-center text-muted">
                    <button class="btn" onclick="window.open('faq');">
                        <i class="bi bi-question-circle-fill h3"></i></button>
                <button class="btn" onclick="window.open('https://www.google.com/maps/place/Chapter+Two+Studio/@-36.847586,174.7649503,15z/data=!4m6!3m5!1s0x6d0d47482d9cfe8d:0xd94e9630993c2a3e!8m2!3d-36.847586!4d174.7649503!16s%2Fg%2F11g1q0t_8y?entry=ttu');">
                    <i class="bi bi-geo-alt-fill h3"></i></button>
                    <button class="btn" onclick="window.open('https://www.instagram.com/sweetchilli.tt/');">
                        <i class="bi bi-instagram h3"></i></button>
        </div>
    </div>
    
</footer>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Sweet Chilli Tattoo - Krissi U.</title>
        <!-- Favicon -->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts -->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap) -->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>

    <body id="page-top">

        <!-- Navigation -->
        {% include 'navbar.html' %}

        <!-- Block Content -->
        {% block content %}
        
        {% endblock content%}

        <!-- Footer-->
        {% include 'footer.html' %}

        <!-- SCRIPTS-->
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/#page-top">
            <img src="{% static 'img/logo2.png' %}" alt="..." width="42" style="opacity: 0.9;"/> Krissi U.</a>
            
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto my-2 my-lg-0">
                <li class="nav-item"><a class="nav-link" href="/#about">About</a></li>
                <li class="nav-item"><a class="nav-link" href="/#portfolio">Portfolio</a></li>
                <li class="nav-item"><a class="nav-link" href="faq">FAQ</a></li>
                <li class="nav-item"><a class="nav-link" href="/#contact">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>